# -*- coding: utf-8 -*-
"""SAVI_MDP_Ames_Housing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qeCDuCwSbDytcI253HzkWkVPiZgrHWXd

# Taller 1 · Corte 3 · Reinforcement Learning · MDP

## Sistema Autónomo de Valuación Inmobiliaria \(SAVI\)

```text
╔══════════════════════════════════════════════════════════════════════╗
║   TALLER 1 - CORTE 3 · REINFORCEMENT LEARNING · MDP                ║
║   Sistema Autónomo de Valuación Inmobiliaria (SAVI)                 ║
║                                                                      ║
║   Integrantes:                                                       ║
║     · Julian Esteban Rincon R.                                       ║
║     · Valeria Larea                                                  ║
║     · Nicolás Garzón                                                 ║
║     · Juan Niño                                                      ║
║                                                                      ║
║   Universidad Sergio Arboleda · Machine Learning Corte 3 · 2026     ║
╚══════════════════════════════════════════════════════════════════════╝

Dataset  : Ames Housing 2006-2024 (20,203 registros)
Modelo   : K-Means (k=6) + XGBoost → R²=0.9609, MAE=$26,752
MDP      : States=6 clusters · Actions={APROBAR,REVISAR,RECHAZAR}
           γ=0.95 · θ=0.0001 · Convergió en 259 iteraciones
```

Este cuaderno organiza el código en celdas ejecutables para correr el flujo completo: limpieza del dataset, clustering con K-Means, entrenamiento con XGBoost, construcción del MDP, Value Iteration, extracción de política óptima y visualización final.

**Archivo requerido:** `ames_combined_2006_2024.csv` debe estar en la misma carpeta del cuaderno, salvo que cambies la variable `DATASET_PATH` en la celda de configuración.

## 0. Dependencias

Ejecuta la siguiente celda solo si tu entorno no tiene instaladas las librerías necesarias. En la mayoría de entornos académicos/Jupyter puede dejarse comentada.
"""

# Descomenta si hace falta instalar dependencias:
# !pip install pandas numpy matplotlib scikit-learn xgboost

"""## PASO 0 — IMPORTS Y CONFIGURACIÓN"""

# PASO 0 · IMPORTS Y CONFIGURACIÓN
# ─────────────────────────────────────────────────────────────────────
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import warnings
import os
import sys
from pathlib import Path
warnings.filterwarnings("ignore")

os.environ.setdefault("LOKY_MAX_CPU_COUNT", "1")
try:
    sys.stdout.reconfigure(encoding="utf-8")
except AttributeError:
    pass

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import mean_absolute_error, r2_score, silhouette_score
import xgboost as xgb

# Parámetros del MDP
GAMMA   = 0.95      # Factor de descuento
THETA   = 0.0001    # Umbral de convergencia para Value Iteration
ACTIONS = ["APROBAR", "REVISAR", "RECHAZAR"]
N_CLUSTERS = 6

# Ruta del dataset. Prioriza AMES_DATASET_PATH si se define en el entorno.
DATASET_CANDIDATES = [
    Path(os.environ["AMES_DATASET_PATH"]) if os.environ.get("AMES_DATASET_PATH") else None,
    Path("ames_combined_2006_2024.csv"),
    Path("data") / "ames_combined_2006_2024.csv",
    Path(r"C:\Users\jrinc\Desktop\Aprendizaje de maquina\ames House Price\ames_combined_2006_2024.csv"),
]
DATASET_PATH = next((p for p in DATASET_CANDIDATES if p and p.exists()), DATASET_CANDIDATES[1])


print("=" * 60)
print("  SAVI — Sistema Autónomo de Valuación Inmobiliaria")
print("  Julian Rincon · Valeria Larea · Nicolás Garzón · Juan Niño")
print("=" * 60)

# ─────────────────────────────────────────────────────────────────────

"""## PASO 1 — CARGA Y LIMPIEZA DEL DATASET"""

# PASO 1 · CARGA Y LIMPIEZA DEL DATASET
# ─────────────────────────────────────────────────────────────────────
print("\n[PASO 1] Cargando y limpiando dataset...")

if not DATASET_PATH.exists():
    expected_paths = "\n".join(f"  - {p}" for p in DATASET_CANDIDATES if p)
    raise FileNotFoundError(
        "No se encontró el archivo CSV de Ames Housing. Ubícalo en una de estas rutas "
        "o define la variable de entorno AMES_DATASET_PATH:\n"
        f"{expected_paths}"
    )

df = pd.read_csv(DATASET_PATH)
print(f"  Dataset fuente: {DATASET_PATH}")
print(f"  Dataset cargado: {df.shape[0]:,} filas x {df.shape[1]} columnas")

# Filtrar outlier extremo (precio > percentil 99.9)
df = df[df["SalePrice"] <= df["SalePrice"].quantile(0.999)].copy()
print(f"  Tras filtrar outliers extremos: {df.shape[0]:,} filas")

# Imputación categórica: ausencia = 'None'
cat_none = ["Alley","BsmtQual","BsmtCond","BsmtExposure","BsmtFinType1",
            "BsmtFinType2","FireplaceQu","GarageType","GarageFinish",
            "GarageQual","GarageCond","PoolQC","Fence","MiscFeature","MasVnrType"]
for c in cat_none:
    if c in df.columns:
        df[c] = df[c].fillna("None")

# Imputación numérica: ausencia = 0
num_zero = ["MasVnrArea","BsmtFinSF1","BsmtFinSF2","BsmtUnfSF","TotalBsmtSF",
            "BsmtFullBath","BsmtHalfBath","GarageYrBlt","GarageArea",
            "GarageCars","WoodDeckSF","OpenPorchSF","EnclosedPorch",
            "3SsnPorch","ScreenPorch","PoolArea"]
for c in num_zero:
    if c in df.columns:
        df[c] = df[c].fillna(0)

# LotFrontage: mediana por vecindario (lógica de negocio)
if "LotFrontage" in df.columns:
    df["LotFrontage"] = df.groupby("Neighborhood")["LotFrontage"].transform(
        lambda x: x.fillna(x.median()))

# Resto: moda para categóricos, mediana para numéricos
for c in df.select_dtypes(include="object").columns:
    df[c] = df[c].fillna(df[c].mode()[0] if not df[c].mode().empty else "Unknown")
for c in df.select_dtypes(include=[np.number]).columns:
    df[c] = df[c].fillna(df[c].median())

# Feature Engineering
if all(c in df.columns for c in ["TotalBsmtSF","1stFlrSF","2ndFlrSF"]):
    df["TotalSF"]     = df["TotalBsmtSF"] + df["1stFlrSF"] + df["2ndFlrSF"]
if "YrSold" in df.columns:
    df["HouseAge"]    = (df["YrSold"] - df["YearBuilt"]).clip(0)
df["QualXArea"]       = df["OverallQual"] * df.get("GrLivArea", pd.Series(0, index=df.index))
df["IsRemodeled"]     = (df["YearBuilt"] != df["YearRemodAdd"]).astype(int)

print("  Limpieza e ingeniería de features completada.")

# ─────────────────────────────────────────────────────────────────────

"""## PASO 2 — DEFINICIÓN DE ESTADOS VÍA K-MEANS"""

# PASO 2 · DEFINICIÓN DE ESTADOS VÍA K-MEANS
# DIFERENCIA CLAVE vs código base: usamos K-Means en lugar de pd.qcut
# K-Means agrupa propiedades por similitud económica real en 265 features
# vs qcut que solo discretiza una variable arbitrariamente
# ─────────────────────────────────────────────────────────────────────
print("\n[PASO 2] Definiendo estados con K-Means (k=6)...")

num_cols = df.select_dtypes(include=[np.number]).drop(
    columns=["Id","SalePrice"], errors="ignore").columns.tolist()

scaler  = StandardScaler()
X_scaled = scaler.fit_transform(df[num_cols].fillna(0))

# Silhouette score para validar k=6
km = KMeans(n_clusters=N_CLUSTERS, n_init=10, random_state=42)
cluster_labels = km.fit_predict(X_scaled)
sil = silhouette_score(X_scaled, cluster_labels, sample_size=3000, random_state=42)

df["state"] = cluster_labels
STATES = sorted(df["state"].unique())

print(f"  K-Means entrenado: k={N_CLUSTERS}, silhouette={sil:.4f}")
print(f"  Estados: {STATES}")
for s in STATES:
    mask = df["state"] == s
    print(f"    S{s}: {mask.sum():,} propiedades ({mask.sum()/len(df)*100:.1f}%) "
          f"· precio medio=${df[mask]['SalePrice'].mean():,.0f}")

# ─────────────────────────────────────────────────────────────────────

"""## PASO 2b — MODELO SUPERVISADO (K-Means + XGBoost híbrido)"""

# PASO 2b · MODELO SUPERVISADO (K-Means + XGBoost híbrido)
# El cluster se usa como feature adicional → mejora el R²
# ─────────────────────────────────────────────────────────────────────
print("\n[PASO 2b] Entrenando modelo híbrido K-Means + XGBoost...")

df_enc = pd.get_dummies(df.drop(columns=["Id","SalePrice"], errors="ignore"), drop_first=True)
df_enc["Cluster"] = cluster_labels  # cluster como feature contextual
X = df_enc.copy()
y = np.log1p(df["SalePrice"].values)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

xgb_model = xgb.XGBRegressor(
    n_estimators=400, learning_rate=0.05, max_depth=6,
    subsample=0.8, colsample_bytree=0.8, random_state=42, verbosity=0)
xgb_model.fit(X_train, y_train)

pred     = xgb_model.predict(X_test)
r2       = r2_score(y_test, pred)
mae      = mean_absolute_error(np.expm1(y_test), np.expm1(pred))
pred_prices = np.expm1(pred)
real_prices = np.expm1(y_test)
errors      = np.abs(pred_prices - real_prices) / real_prices

print(f"  XGBoost entrenado: R²={r2:.4f}, MAE=${mae:,.0f}")

# Asignar clusters al test set
test_indices   = X_test.index
test_clusters  = df.loc[test_indices, "state"].values

# ─────────────────────────────────────────────────────────────────────

"""## PASO 3a — FUNCIÓN DE RECOMPENSA"""

# PASO 3a · FUNCIÓN DE RECOMPENSA
# DIFERENCIA vs código base: en lugar de precio_ciudad - farmprice,
# usamos f(error%, accion) basada en costos reales del proceso de tasacion
# ─────────────────────────────────────────────────────────────────────
print("\n[PASO 3a] Calculando tabla de recompensas R[s][a]...")

def calc_reward(error_pct, action):
    """
    Función de recompensa económica para el agente SAVI.

    Args:
        error_pct : float  — error relativo |pred-real|/real
        action    : str    — 'APROBAR', 'REVISAR' o 'RECHAZAR'

    Returns:
        float — recompensa en unidades monetarias normalizadas

    Justificación:
        APROBAR error>25% → -2000: diferencia >$50K en prop. media
        REVISAR → -150: costo fijo de tasador humano
        RECHAZAR datos insuf. → +50: evita error catastrófico
    """
    if action == "APROBAR":
        if error_pct < 0.10:
            return +200   # valuación correcta
        elif error_pct < 0.25:
            return -500   # error moderado, corrección necesaria
        else:
            return -2000  # error grave, posible litigio
    elif action == "REVISAR":
        # Si el modelo habría acertado: se perdió tiempo (-150)
        # Si el modelo habría fallado: la revisión aportó valor (-50)
        return -150 if error_pct < 0.10 else -50
    elif action == "RECHAZAR":
        # Correcto si datos eran insuficientes (error alto)
        return +50 if error_pct > 0.20 else -200

# Construir R_dict[s][a] = recompensa promedio
R_dict = {s: {} for s in STATES}
for s in STATES:
    mask = test_clusters == s
    if mask.sum() == 0:
        for a in ACTIONS:
            R_dict[s][a] = 0
        continue
    s_errors = errors[mask]
    for a in ACTIONS:
        rewards = [calc_reward(e, a) for e in s_errors]
        R_dict[s][a] = np.mean(rewards)
    print(f"  S{s}: APROBAR={R_dict[s]['APROBAR']:.1f} | "
          f"REVISAR={R_dict[s]['REVISAR']:.1f} | RECHAZAR={R_dict[s]['RECHAZAR']:.1f}")

# ─────────────────────────────────────────────────────────────────────

"""## PASO 3b — TABLA DE TRANSICIÓN P(s'|s)"""

# PASO 3b · TABLA DE TRANSICIÓN P(s'|s)
# Opción A: conteo histórico con shift(-1)  ← misma lógica que código base
# Opción B: XGBoost valida las probabilidades calculadas
# ─────────────────────────────────────────────────────────────────────
print("\n[PASO 3b] Construyendo tabla de transición P(s'|s)...")

df["next_state"] = df["state"].shift(-1)
df_tr = df.dropna(subset=["next_state"]).copy()
df_tr["next_state"] = df_tr["next_state"].astype(int)

# Contar transiciones
tc = df_tr.groupby(["state", "next_state"]).size()
st = df_tr.groupby("state").size()

# Normalizar → probabilidades
P_dict = {s: {} for s in STATES}
for (s, ns), cnt in tc.items():
    P_dict[int(s)][int(ns)] = cnt / st[s]

print("  Tabla P(s'|s) calculada:")
print(f"  {'Estado':<8}", end="")
for ns in STATES:
    print(f"{'→S'+str(ns):<10}", end="")
print()
for s in STATES:
    print(f"  S{s:<7}", end="")
    for ns in STATES:
        p = P_dict[s].get(ns, 0)
        print(f"{p:.3f}    ", end="")
    print()

# ─────────────────────────────────────────────────────────────────────

"""## PASO 4 — VALUE ITERATION (algoritmo de Bellman)"""

# PASO 4 · VALUE ITERATION (algoritmo de Bellman)
# Este paso es idéntico al código base — si los pasos 1-3 son correctos,
# Value Iteration funciona directamente sobre cualquier MDP bien definido
# ──────────────────────────────────────────────────────────────────
print(f"\n[PASO 4] Value Iteration (γ={GAMMA}, θ={THETA})...")

V = {s: 0 for s in STATES}
iteration = 0

while True:
    iteration += 1
    delta  = 0
    V_new  = V.copy()

    for s in STATES:
        q_sa = {}
        for a in ACTIONS:
            reward = R_dict[s].get(a, 0)

            # Valor futuro esperado: Σ P(s'|s) * V(s')
            efv = sum(P_dict[s].get(ns, 0) * V.get(ns, 0) for ns in STATES)

            # Ecuación de Bellman: Q(s,a) = R(s,a) + γ * E[V(s')]
            q_sa[a] = reward + GAMMA * efv

        # Maximizar sobre acciones
        V_new[s] = max(q_sa.values())
        delta = max(delta, abs(V[s] - V_new[s]))

    V = V_new
    if delta < THETA:
        break

print(f"  Convergió en {iteration} iteraciones")
print(f"  V*(s) por estado:")
for s in STATES:
    print(f"    S{s}: V*={V[s]:.2f}")

# ──────────────────────────────────────────────────────────────────

"""## PASO 5 — EXTRACCIÓN DE POLÍTICA ÓPTIMA π*(s)"""

# PASO 5 · EXTRACCIÓN DE POLÍTICA ÓPTIMA π*(s)
# ─────────────────────────────────────────────────────────────────────
print("\n[PASO 5] Extrayendo política óptima π*(s)...")

politica_optima = {}
Q_table = {}  # Para análisis

for s in STATES:
    q_sa = {}
    for a in ACTIONS:
        reward = R_dict[s].get(a, 0)
        efv    = sum(P_dict[s].get(ns, 0) * V.get(ns, 0) for ns in STATES)
        q_sa[a] = reward + GAMMA * efv
    Q_table[s]          = q_sa
    politica_optima[s]  = max(q_sa, key=q_sa.get)

print("\n  POLÍTICA ÓPTIMA π*(s):")
print(f"  {'Estado':<30} {'π*(s)':<15} {'Q(APROBAR)':<14} {'Q(REVISAR)':<14} {'Q(RECHAZAR)'}")
print("  " + "-"*82)
for s in STATES:
    q = Q_table[s]
    best = politica_optima[s]
    print(f"  S{s} ({df[df['state']==s]['SalePrice'].mean():>8,.0f} precio medio) "
          f"→ {best:<15} "
          f"{q['APROBAR']:>10.1f}    "
          f"{q['REVISAR']:>10.1f}    "
          f"{q['RECHAZAR']:>10.1f}")

# ─────────────────────────────────────────────────────────────────────

"""## GRÁFICA 1 — DISTRIBUCIÓN DE POLÍTICA (gráfico que pide el taller)"""

# GRÁFICA 1 · DISTRIBUCIÓN DE POLÍTICA (gráfico que pide el taller)
# ─────────────────────────────────────────────────────────────────────
print("\n[GRÁFICAS] Generando visualizaciones...")

policy_colors = {"APROBAR": "#00FF9C", "REVISAR": "#FFB300", "RECHAZAR": "#FF4D6D"}
state_labels  = [f"S{s}" for s in STATES]
policy_list   = [politica_optima[s] for s in STATES]
bar_colors    = [policy_colors[p] for p in policy_list]

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.patch.set_facecolor("#090E1A")

# Gráfica izquierda: política por estado
ax1 = axes[0]
ax1.set_facecolor("#0F1829")
bars = ax1.bar(state_labels, [1]*len(STATES), color=bar_colors, edgecolor="#1A3355", linewidth=1.2, width=0.6)
ax1.set_title("Distribución de la Política Óptima π*(s)",
              color="white", fontsize=13, fontweight="bold", pad=15)
ax1.set_xlabel("Estado (Cluster K-Means)", color="#94A3B8", fontsize=11)
ax1.set_ylabel("Acción asignada", color="#94A3B8", fontsize=11)
ax1.set_ylim(0, 1.4)
ax1.set_yticks([])
ax1.tick_params(colors="#94A3B8")
for spine in ax1.spines.values():
    spine.set_edgecolor("#112240")

# Etiquetas encima de barras
for i, (bar, pol, s) in enumerate(zip(bars, policy_list, STATES)):
    pct = df[df["state"]==s].shape[0] / len(df) * 100
    ax1.text(bar.get_x() + bar.get_width()/2, 1.08, pol,
             ha="center", va="bottom", color=policy_colors[pol],
             fontsize=10, fontweight="bold")
    ax1.text(bar.get_x() + bar.get_width()/2, 0.5, f"{pct:.1f}%",
             ha="center", va="center", color="white", fontsize=9)

legend_patches = [mpatches.Patch(color=v, label=k) for k, v in policy_colors.items()]
ax1.legend(handles=legend_patches, loc="upper right",
           facecolor="#0F1829", edgecolor="#1A3355", labelcolor="white")

# Gráfica derecha: V*(s) por estado
ax2 = axes[1]
ax2.set_facecolor("#0F1829")
v_values = [V[s] for s in STATES]
v_colors = [policy_colors[politica_optima[s]] for s in STATES]
bars2 = ax2.barh(state_labels, [abs(v) for v in v_values],
                  color=v_colors, edgecolor="#1A3355", linewidth=1.2, height=0.55)
ax2.set_title("V*(s) — Valor Óptimo por Estado",
              color="white", fontsize=13, fontweight="bold", pad=15)
ax2.set_xlabel("Valor absoluto de V*(s)", color="#94A3B8", fontsize=11)
ax2.set_ylabel("Estado", color="#94A3B8", fontsize=11)
ax2.tick_params(colors="#94A3B8")
for spine in ax2.spines.values():
    spine.set_edgecolor("#112240")

for bar, v, s in zip(bars2, v_values, STATES):
    ax2.text(bar.get_width() + 10, bar.get_y() + bar.get_height()/2,
             f"V*={v:.1f}", va="center", color="white", fontsize=9)

ax2.legend(handles=legend_patches, loc="lower right",
           facecolor="#0F1829", edgecolor="#1A3355", labelcolor="white")

plt.tight_layout(pad=2.5)
plt.suptitle("Julian Rincon · Valeria Larea · Nicolás Garzón · Juan Niño  |  SAVI MDP — Ames Housing 2006-2024",
             y=1.02, color="#5A7A9B", fontsize=9)
plt.savefig("MDP_SAVI_politica.png", dpi=150, bbox_inches="tight",
            facecolor="#090E1A", edgecolor="none")
plt.show()
print("  Gráfica guardada: MDP_SAVI_politica.png")

# ─────────────────────────────────────────────────────────────────────

"""## ANÁLISIS FINAL — LAS 3 REGLAS DE ORO"""

# ANÁLISIS FINAL · LAS 3 REGLAS DE ORO
# ─────────────────────────────────────────────────────────────────────
print("\n" + "="*60)
print("  ANÁLISIS: LAS 3 REGLAS DE ORO DEL AGENTE SAVI")
print("="*60)

print("""
  REGLA 1 — S3 siempre RECHAZA (la más contraintuitiva)
  ──────────────────────────────────────────────────
  Solo 7 propiedades históricas (0.03% del dataset).
  R(APROBAR) = -2,000  vs  R(RECHAZAR) = +50
  El agente descubrió que pedir más documentación (+$50)
  y esperar produce mayor valor futuro descontado que
  valuar con incertidumbre total. Emergió sola de Bellman.

  REGLA 2 — El mercado mayoritario siempre APRUEBA
  ──────────────────────────────────────────────────
  S1+S4+S5 = 93.1% del dataset siempre APRUEBAN.
  R(APROBAR) = -$7 a -$76  <<  R(REVISAR) = -$119 a -$127
  El XGBoost es muy preciso en estos clusters porque la
  mayor parte del entrenamiento les corresponde.
  Automatización máxima donde el modelo es confiable.

  REGLA 3 — La incertidumbre activa la revisión
  ───────────────────────────────────────────────
  S0 y S2 siempre REVISAN.
  S0: R(APROBAR)=-169.9  vs  R(REVISAR)=-113.6
  S2: R(APROBAR)=-136.1  vs  R(REVISAR)=-113.9
  En ambos casos el costo esperado de APROBAR supera
  al de REVISAR. El agente aprende a proteger los
  segmentos con mayor heterogeneidad interna.
""")

print("="*60)
print(f"  RESULTADO FINAL:")
aprobar_pct  = sum(df[df["state"]==s].shape[0] for s in STATES if politica_optima[s]=="APROBAR")  / len(df) * 100
revisar_pct  = sum(df[df["state"]==s].shape[0] for s in STATES if politica_optima[s]=="REVISAR")  / len(df) * 100
rechazar_pct = sum(df[df["state"]==s].shape[0] for s in STATES if politica_optima[s]=="RECHAZAR") / len(df) * 100
print(f"  APROBAR  : {aprobar_pct:.1f}% de propiedades — automatización directa")
print(f"  REVISAR  : {revisar_pct:.1f}% de propiedades — revisión humana selectiva")
print(f"  RECHAZAR : {rechazar_pct:.2f}% de propiedades — solicitar más datos")
print("="*60)
print("\n  SAVI completado exitosamente.")
print("  Julian Rincon · Valeria Larea · Nicolás Garzón · Juan Niño")
print("  Universidad Sergio Arboleda · Corte 3 · 2026")
